pipeline {
    agent any

    environment {
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
    }

    stages {
        stage('Setup & Test') {
            steps {
                dir('PyTest DQ Framework') {
                    sh '''
                        apt-get update -qq && apt-get install -y python3 python3-venv python3-pip
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt

                        pytest tests -m "parquet_data" \
                            --db_host="postgres" \
                            --db_port="5432" \
                            --db_name="mydatabase" \
                            --db_user=$POSTGRES_SECRET_USR \
                            --db_password=$POSTGRES_SECRET_PSW \
                            --html=html_report/report.html \
                            --self-contained-html
                            -s
                    '''
                }
            }
        }

        stage('Archive Test Report') {
            steps {
                dir('PyTest DQ Framework') {
                    archiveArtifacts artifacts: 'html_report/**', allowEmptyArchive: true

                    publishHTML(target: [
                        allowMissing: false,
                        keepAll: true,
                        reportDir: 'html_report',
                        reportFiles: 'report.html',
                        reportName: 'PyTest DQ Report'
                    ])
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}